#dev end point latest
#DEV_SERVER_URL="https://devezazi.intelehealth.org"
#DEV_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com"
#DEV_FB_RT_DB="devezazi_intelehealth_org"
#DEV_LIVE_KIT_URL="wss://devezazi.intelehealth.org:9090"
#DEV_SOCKET_URL="https://devezazi.intelehealth.org:3004";
#Production

###EZAZI###

EZAZI_PROD_SERVER_URL="https://ezazi.intelehealth.org"
EZAZI_PROD_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com"
EZAZI_PROD_FB_RT_DB="testezazi_intelehealth_org"
EZAZI_PROD_LIVE_KIT_URL="wss://ezazi.intelehealth.org:9090"
EZAZI_PROD_SOCKET_URL="https://ezazi.intelehealth.org:3004";

EZAZI_STAGE_SERVER_URL="https://ezazi.intelehealth.org"
EZAZI_STAGE_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com"
EZAZI_STAGE_FB_RT_INSTANCE="testezazi.intelehealth.org"
EZAZI_STAGE_LIVE_KIT_URL="wss://ezazi.intelehealth.org:9090"
EZAZI_STAGE_SOCKET_URL="https://ezazi.intelehealth.org:3004";

#dev end point latest
EZAZI_DEV_SERVER_URL="https://testezazi.intelehealth.org"
EZAZI_DEV_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com/"
EZAZI_DEV_FB_RT_INSTANCE="testezazi.intelehealth.org"
EZAZI_DEV_LIVE_KIT_URL="wss://testezazi.intelehealth.org:9090"
EZAZI_DEV_SOCKET_URL="https://testezazi.intelehealth.org:3004";

####ELCG###

ELCG_PROD_SERVER_URL="https://ezazi.intelehealth.org"
ELCG_PROD_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com"
ELCG_PROD_FB_RT_INSTANCE="testezazi.intelehealth.org"
ELCG_PROD_LIVE_KIT_URL="wss://ezazi.intelehealth.org:9090"
ELCG_PROD_SOCKET_URL="https://ezazi.intelehealth.org:3004";

ELCG_STAGE_SERVER_URL="https://ezazi.intelehealth.org"
ELCG_STAGE_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com"
ELCG_STAGE_FB_RT_INSTANCE="testezazi.intelehealth.org"
ELCG_STAGE_LIVE_KIT_URL="wss://ezazi.intelehealth.org:9090"
ELCG_STAGE_SOCKET_URL="https://ezazi.intelehealth.org:3004";

#dev end point latest
ELCG_DEV_SERVER_URL="https://testezazi.intelehealth.org"
ELCG_DEV_REAL_TIME_FB_URL="https://ezazi-8712a-default-rtdb.firebaseio.com"
ELCG_DEV_FB_RT_INSTANCE="testezazi.intelehealth.org"
ELCG_DEV_LIVE_KIT_URL="wss://testezazi.intelehealth.org:9090"
ELCG_DEV_SOCKET_URL="https://testezazi.intelehealth.org:3004";